import type { TranscriptionMode } from "./foundation";

export function getTranscriptionModeLabel(mode: TranscriptionMode) {
  if (mode === "python") return "Python Whisper service";
  if (mode === "openai") return "real OpenAI transcription";
  return "demo fallback";
}

export function getTranscriptionModeDescription(mode: TranscriptionMode) {
  if (mode === "python") {
    return "Captions were generated by the Python Whisper service, which is best for heavier Arabic transcription.";
  }
  if (mode === "openai") {
    return "Captions were generated from the uploaded video's audio.";
  }
  return "Demo captions are active. Add PYTHON_AI_SERVICE_URL or OPENAI_API_KEY for real audio transcription.";
}

export function normalizeHexColor(value?: string) {
  if (!value || value.includes("{{") || !/^#[0-9a-f]{6}$/i.test(value)) return "#8ef7c2";
  return value;
}

export function formatDuration(seconds: number) {
  const minutes = Math.floor(seconds / 60);
  const rest = Math.floor(seconds % 60);
  return `${minutes.toString().padStart(2, "0")}:${rest.toString().padStart(2, "0")}`;
}

export function formatBytes(bytes: number) {
  if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
